/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DAOViews;

/**
 *
 * @author Nolasco Dos Anjos
 */
public class TelaLivro extends javax.swing.JFrame {

    /**
     * Creates new form TelaFunc
     */
    public TelaLivro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jTxtAutor = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jTxtAnoLanc = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jTxtTitulo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbtApagar = new javax.swing.JButton();
        jbtEditar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jtxtPesq = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jcbEdicao = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CADASTRO FUNCIONÁRIO");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CADASTRO DE LIVROS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Autor:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ano de lançamento:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 150, 30));

        jTextField1.setBackground(new java.awt.Color(51, 102, 255));
        jTextField1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 50, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 50, 10));

        jTxtAutor.setBackground(new java.awt.Color(51, 102, 255));
        jTxtAutor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jTxtAutor.setForeground(new java.awt.Color(255, 255, 255));
        jTxtAutor.setBorder(null);
        jPanel1.add(jTxtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 200, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 200, 10));

        jTxtAnoLanc.setBackground(new java.awt.Color(51, 102, 255));
        jTxtAnoLanc.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jTxtAnoLanc.setForeground(new java.awt.Color(255, 255, 255));
        jTxtAnoLanc.setBorder(null);
        jPanel1.add(jTxtAnoLanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 70, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 70, 10));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Título:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        jTxtTitulo.setBackground(new java.awt.Color(51, 102, 255));
        jTxtTitulo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jTxtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jTxtTitulo.setBorder(null);
        jPanel1.add(jTxtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 240, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 240, 10));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Edição:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 60, 40));

        jTable1.setBackground(new java.awt.Color(51, 102, 255));
        jTable1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 930, 310));

        jbNovo.setBackground(new java.awt.Color(255, 255, 255));
        jbNovo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Add User Group Woman Man_40px_1.png"))); // NOI18N
        jbNovo.setBorder(null);
        jPanel1.add(jbNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 30, 30));

        jbSalvar.setBackground(new java.awt.Color(255, 255, 255));
        jbSalvar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Save.png"))); // NOI18N
        jbSalvar.setBorder(null);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jbSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 30, 30));

        jbtApagar.setBackground(new java.awt.Color(255, 255, 255));
        jbtApagar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jbtApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Delete_48px.png"))); // NOI18N
        jbtApagar.setBorder(null);
        jbtApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtApagarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 30, 30));

        jbtEditar.setBackground(new java.awt.Color(255, 255, 255));
        jbtEditar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jbtEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Edit File_40px.png"))); // NOI18N
        jbtEditar.setBorder(null);
        jPanel1.add(jbtEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 30, 30));

        jbtCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jbtCancelar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jbtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Close Window_48px_2.png"))); // NOI18N
        jbtCancelar.setBorder(null);
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 30, 30));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Código:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        jButton14.setBackground(new java.awt.Color(255, 255, 255));
        jButton14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Close Window_48px_2.png"))); // NOI18N
        jButton14.setBorder(null);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 30, 30));

        jtxtPesq.setBackground(new java.awt.Color(51, 102, 255));
        jtxtPesq.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jtxtPesq.setForeground(new java.awt.Color(255, 255, 255));
        jtxtPesq.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPesq.setBorder(null);
        jPanel1.add(jtxtPesq, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 230, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 270, 10));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Search_48px.png"))); // NOI18N
        jLabel8.setToolTipText("Procurar");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 40, 50));

        jcbEdicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1º", "2º", "3º", "4º", "5º", "6º", "7º", "8º", "9º", "10º", "11º", "Outro" }));
        jcbEdicao.setSelectedIndex(-1);
        jPanel1.add(jcbEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 70, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(930, 531));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbtApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtApagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtApagarActionPerformed

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTxtAnoLanc;
    private javax.swing.JTextField jTxtAutor;
    private javax.swing.JTextField jTxtTitulo;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbtApagar;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtEditar;
    private javax.swing.JComboBox<String> jcbEdicao;
    private javax.swing.JTextField jtxtPesq;
    // End of variables declaration//GEN-END:variables
}
