/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DAOViews;

import DAOConection.Conexao;
import DAOControl.ControlUser;
import DAOModel.ModelTable;
import DAOModel.ModelUsuario;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Nolasco Dos Anjos
 */
public class TelaUser extends javax.swing.JFrame {

    ModelUsuario mu = new ModelUsuario();
    ControlUser cu = new ControlUser();
    Conexao c = new Conexao();
    int flag = 0;
    /**
     * Creates new form TelaFunc
     */
    public TelaUser() {
        initComponents();
        preencherTabela("select * from usuario order by nome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtCod = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jTxtNbi = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jcGenero = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jTxtContacto = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jcCategoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbUser = new javax.swing.JTable();
        jbNovo = new javax.swing.JButton();
        jbApagar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jBtSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTxtCurso = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jtXtpesq = new javax.swing.JTextField();
        jlPesq = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jcEstado = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jTxtAno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CADASTRO FUNCIONÁRIO");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gênero:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, 20));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CADASTRO USUÁRIO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nº BI:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, 30));

        jTxtCod.setBackground(new java.awt.Color(51, 102, 255));
        jTxtCod.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jTxtCod.setForeground(new java.awt.Color(255, 255, 255));
        jTxtCod.setBorder(null);
        jPanel1.add(jTxtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 50, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 50, 10));

        jTxtNbi.setBackground(new java.awt.Color(51, 102, 255));
        jTxtNbi.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jTxtNbi.setForeground(new java.awt.Color(255, 255, 255));
        jTxtNbi.setBorder(null);
        jTxtNbi.setEnabled(false);
        jPanel1.add(jTxtNbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 200, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 200, 10));

        jcGenero.setBackground(new java.awt.Color(51, 102, 255));
        jcGenero.setForeground(new java.awt.Color(255, 255, 255));
        jcGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        jcGenero.setSelectedIndex(-1);
        jcGenero.setEnabled(false);
        jPanel1.add(jcGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 60, 20));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nome:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        jTxtNome.setBackground(new java.awt.Color(51, 102, 255));
        jTxtNome.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jTxtNome.setForeground(new java.awt.Color(255, 255, 255));
        jTxtNome.setBorder(null);
        jTxtNome.setEnabled(false);
        jPanel1.add(jTxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 240, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 240, 10));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefone:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 30));

        jTxtContacto.setBackground(new java.awt.Color(51, 102, 255));
        jTxtContacto.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jTxtContacto.setForeground(new java.awt.Color(255, 255, 255));
        jTxtContacto.setBorder(null);
        jTxtContacto.setEnabled(false);
        jPanel1.add(jTxtContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 190, 20));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 190, 10));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Categoria:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, -1, -1));

        jcCategoria.setBackground(new java.awt.Color(51, 102, 255));
        jcCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jcCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Professor", "Estudante" }));
        jcCategoria.setSelectedIndex(-1);
        jcCategoria.setEnabled(false);
        jPanel1.add(jcCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 110, -1));

        jTbUser.setBackground(new java.awt.Color(51, 102, 255));
        jTbUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jTbUser.setForeground(new java.awt.Color(255, 255, 255));
        jTbUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTbUser);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 930, 310));

        jbNovo.setBackground(new java.awt.Color(255, 255, 255));
        jbNovo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Add User Group Woman Man_40px_1.png"))); // NOI18N
        jbNovo.setBorder(null);
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });
        jPanel1.add(jbNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 30, 30));

        jbApagar.setBackground(new java.awt.Color(255, 255, 255));
        jbApagar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jbApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Delete_48px.png"))); // NOI18N
        jbApagar.setBorder(null);
        jbApagar.setEnabled(false);
        jbApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbApagarActionPerformed(evt);
            }
        });
        jPanel1.add(jbApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 30, 30));

        jbEditar.setBackground(new java.awt.Color(255, 255, 255));
        jbEditar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Edit File_40px.png"))); // NOI18N
        jbEditar.setBorder(null);
        jbEditar.setEnabled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jbEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 30, 30));

        jBtSalvar.setBackground(new java.awt.Color(255, 255, 255));
        jBtSalvar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jBtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Save.png"))); // NOI18N
        jBtSalvar.setBorder(null);
        jBtSalvar.setEnabled(false);
        jBtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jBtSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 30, 30));

        jbCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jbCancelar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Close Window_48px_2.png"))); // NOI18N
        jbCancelar.setBorder(null);
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jbCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 30, 30));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Código:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        jButton14.setBackground(new java.awt.Color(255, 255, 255));
        jButton14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Close Window_48px_2.png"))); // NOI18N
        jButton14.setBorder(null);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 30, 30));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Curso:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, 30));

        jTxtCurso.setBackground(new java.awt.Color(51, 102, 255));
        jTxtCurso.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jTxtCurso.setForeground(new java.awt.Color(255, 255, 255));
        jTxtCurso.setBorder(null);
        jTxtCurso.setEnabled(false);
        jPanel1.add(jTxtCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 190, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 190, 10));

        jtXtpesq.setBackground(new java.awt.Color(51, 102, 255));
        jtXtpesq.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jtXtpesq.setForeground(new java.awt.Color(255, 255, 255));
        jtXtpesq.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtXtpesq.setBorder(null);
        jPanel1.add(jtXtpesq, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 230, 30));

        jlPesq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Search_48px.png"))); // NOI18N
        jlPesq.setToolTipText("Procurar");
        jlPesq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlPesq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlPesqMouseClicked(evt);
            }
        });
        jPanel1.add(jlPesq, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 40, 50));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 270, 10));

        jComboBox3.setBackground(new java.awt.Color(51, 102, 255));
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Professor", "Estudante" }));
        jComboBox3.setSelectedIndex(-1);
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 110, -1));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Gênero:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, 20));

        jComboBox4.setBackground(new java.awt.Color(51, 102, 255));
        jComboBox4.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        jComboBox4.setSelectedIndex(-1);
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 60, 20));

        jcEstado.setBackground(new java.awt.Color(51, 102, 255));
        jcEstado.setForeground(new java.awt.Color(255, 255, 255));
        jcEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISPM", "Visita" }));
        jcEstado.setSelectedIndex(-1);
        jcEstado.setEnabled(false);
        jPanel1.add(jcEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 60, 20));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Estado:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, -1, 20));

        jTxtAno.setBackground(new java.awt.Color(51, 102, 255));
        jTxtAno.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jTxtAno.setForeground(new java.awt.Color(255, 255, 255));
        jTxtAno.setBorder(null);
        jTxtAno.setEnabled(false);
        jPanel1.add(jTxtAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 50, 20));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ano:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, 30));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 50, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(930, 531));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbApagarActionPerformed
        int resposta = 0;
        JOptionPane.showConfirmDialog(rootPane, "Deseja realmente eliminar Dados?");
        if(resposta == JOptionPane.YES_OPTION){
            mu.setCod(Integer.parseInt(jTxtCod.getText()));
            cu.Apagar(mu);
            jTxtNome.setText("");
            jTxtNbi.setText("");
            jcGenero.setSelectedIndex(-1);
            jTxtContacto.setText("");
            jcCategoria.setSelectedIndex(-1);
            jTxtCurso.setText("");
            jTxtAno.setText("");
            jcEstado.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_jbApagarActionPerformed

    private void jBtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSalvarActionPerformed
       if(flag==1){
            mu.setNome(jTxtNome.getText());
            mu.setnBI(jTxtNbi.getText());
            mu.setGenero(String.valueOf(jcGenero.getSelectedIndex()));
            mu.setContacto(Integer.parseInt(jTxtContacto.getText()));
            mu.setCategoria(String.valueOf(jcCategoria.getSelectedItem()));
            mu.setCurso(jTxtCurso.getText());
            mu.setAno(Integer.parseInt(jTxtAno.getText()));
            mu.setEstado(String.valueOf(jcEstado.getSelectedItem()));
            cu.Salvar(mu);
            jTxtNome.setText("");
            jTxtNbi.setText("");
            jcGenero.setSelectedIndex(-1);
            jTxtContacto.setText("");
            jcCategoria.setSelectedIndex(-1);
            jTxtCurso.setText("");
            jTxtAno.setText("");
            jcEstado.setSelectedIndex(-1);
       }else{
            mu.setNome(jTxtNome.getText());
            mu.setnBI(jTxtNbi.getText());
            mu.setGenero(String.valueOf(jcGenero.getSelectedIndex()));
            mu.setContacto(Integer.parseInt(jTxtContacto.getText()));
            mu.setCategoria(String.valueOf(jcCategoria.getSelectedItem()));
            mu.setCurso(jTxtCurso.getText());
            mu.setAno(Integer.parseInt(jTxtAno.getText()));
            mu.setEstado(String.valueOf(jcEstado.getSelectedItem()));
            cu.Editar(mu);
            jTxtNome.setEnabled(false);
            jTxtNbi.setEnabled(false);
            jcGenero.setEnabled(false);
            jTxtContacto.setEnabled(false);
            jcCategoria.setEnabled(false);
            jTxtCurso.setEnabled(false);
            jTxtAno.setEnabled(false);
            jcEstado.setEnabled(false);
       }
            
            
        
    }//GEN-LAST:event_jBtSalvarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
            jTxtNome.setEnabled(!true);
            jTxtNbi.setEnabled(!true);
            jcGenero.setEnabled(!true);
            jTxtContacto.setEnabled(!true);
            jcCategoria.setEnabled(!true);
            jTxtCurso.setEnabled(!true);
            jTxtAno.setEnabled(!true);
            jcEstado.setEnabled(!true);
            jBtSalvar.setEnabled(!true);
            jbCancelar.setEnabled(!true);
            jbNovo.setEnabled(!false);
            jbEditar.setEnabled(false);
            jbApagar.setEnabled(false);
            jTxtNome.setText("");
            jTxtNbi.setText("");
            jcGenero.setSelectedIndex(-1);
            jTxtContacto.setText("");
            jcCategoria.setSelectedIndex(-1);
            jTxtCurso.setText("");
            jTxtAno.setText("");
            jcEstado.setSelectedIndex(-1);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
       flag=1;
            jTxtNome.setEnabled(true);
            jTxtNbi.setEnabled(true);
            jcGenero.setEnabled(true);
            jTxtContacto.setEnabled(true);
            jcCategoria.setEnabled(true);
            jTxtCurso.setEnabled(true);
            jTxtAno.setEnabled(true);
            jcEstado.setEnabled(true);
            jBtSalvar.setEnabled(true);
            jbCancelar.setEnabled(true);
            jbNovo.setEnabled(false);
            jTxtNome.setText("");
            jTxtNbi.setText("");
            jcGenero.setSelectedIndex(-1);
            jTxtContacto.setText("");
            jcCategoria.setSelectedIndex(-1);
            jTxtCurso.setText("");
            jTxtAno.setText("");
            jcEstado.setSelectedIndex(-1);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jlPesqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlPesqMouseClicked
       mu.setPesquisa(jtXtpesq.getText());
       ModelUsuario mus = cu.buscarFunc(mu);
        jTxtNome.setText(mus.getNome());
        jTxtCod.setText(String.valueOf(mus.getCod()));
        jTxtNbi.setText(mus.getnBI());
        jcGenero.setSelectedItem(mus.getGenero());
        jTxtContacto.setText(String.valueOf(mus.getContacto()));
        jTxtCurso.setText(mus.getCurso());
        jcCategoria.setSelectedItem(mus.getCategoria());
        jTxtAno.setText(String.valueOf(mus.getAno()));
        jcEstado.setSelectedItem(mus.getEstado());
        jbEditar.setEnabled(true);
        jbApagar.setEnabled(true);
        jbNovo.setEnabled(false);
    }//GEN-LAST:event_jlPesqMouseClicked

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
            flag=2;
            jTxtNome.setEnabled(true);
            jTxtNbi.setEnabled(true);
            jcGenero.setEnabled(true);
            jTxtContacto.setEnabled(true);
            jcCategoria.setEnabled(true);
            jTxtCurso.setEnabled(true);
            jTxtAno.setEnabled(true);
            jcEstado.setEnabled(true);
            jBtSalvar.setEnabled(true);
            jbCancelar.setEnabled(true);
            jbNovo.setEnabled(false);
            jbEditar.setEnabled(false);
            jTxtNome.setText("");
            jTxtNbi.setText("");
            jcGenero.setSelectedIndex(-1);
            jTxtContacto.setText("");
            jcCategoria.setSelectedIndex(-1);
            jTxtCurso.setText("");
            jTxtAno.setText("");
            jcEstado.setSelectedIndex(-1);
    }//GEN-LAST:event_jbEditarActionPerformed
 public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String[]{"ID", "Nome", "NBI", "Gênero", "Contacto", "Categoria", "Curso", "Ano_Frequ", "Estado"};
        c.conexao();
        c.executSql(Sql);
        
        try {
            c.rs.first();
            do{
                dados.add(new Object[] {c.rs.getInt("id"),c.rs.getString("nome"),c.rs.getString("nBI"), c.rs.getString("sexo"),
                c.rs.getInt("phone"),c.rs.getString("category"),c.rs.getString("curso"),c.rs.getString("classe"),c.rs.getString("estado")});
            }while(c.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preecher Tabela"+ex);
        }
        ModelTable mt = new ModelTable(dados, colunas);
        jTbUser.setModel(mt);
        jTbUser.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTbUser.getColumnModel().getColumn(0).setResizable(false);
        jTbUser.getColumnModel().getColumn(1).setPreferredWidth(160);
        jTbUser.getColumnModel().getColumn(1).setResizable(false);
        jTbUser.getColumnModel().getColumn(2).setPreferredWidth(130);
        jTbUser.getColumnModel().getColumn(2).setResizable(false);
        jTbUser.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTbUser.getColumnModel().getColumn(3).setResizable(false);
        jTbUser.getColumnModel().getColumn(4).setPreferredWidth(130);
        jTbUser.getColumnModel().getColumn(4).setResizable(false);
        jTbUser.getColumnModel().getColumn(5).setPreferredWidth(160);
        jTbUser.getColumnModel().getColumn(5).setResizable(false);
        jTbUser.getColumnModel().getColumn(6).setPreferredWidth(95);
        jTbUser.getColumnModel().getColumn(6).setResizable(false);
        jTbUser.getColumnModel().getColumn(7).setPreferredWidth(102);
        jTbUser.getColumnModel().getColumn(7).setResizable(false);
        jTbUser.getColumnModel().getColumn(8).setPreferredWidth(69);
        jTbUser.getColumnModel().getColumn(8).setResizable(false);
        jTbUser.getTableHeader().setReorderingAllowed(false);
        jTbUser.setAutoResizeMode(jTbUser.AUTO_RESIZE_OFF);
        jTbUser.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        c.desconectar();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtSalvar;
    private javax.swing.JButton jButton14;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTbUser;
    private javax.swing.JTextField jTxtAno;
    private javax.swing.JTextField jTxtCod;
    private javax.swing.JTextField jTxtContacto;
    private javax.swing.JTextField jTxtCurso;
    private javax.swing.JTextField jTxtNbi;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JButton jbApagar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JComboBox<String> jcCategoria;
    private javax.swing.JComboBox<String> jcEstado;
    private javax.swing.JComboBox<String> jcGenero;
    private javax.swing.JLabel jlPesq;
    private javax.swing.JTextField jtXtpesq;
    // End of variables declaration//GEN-END:variables
}
