/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DAOViews;

import DAOControl.Utilitarios;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Nolasco Dos Anjos
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        Utilitarios u = new Utilitarios();
        u.InsererIcone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        pFundo = new javax.swing.JPanel();
        pUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelRedifinir = new javax.swing.JLabel();
        jLabelSair = new javax.swing.JLabel();
        jLabelLogar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pFundo.setBackground(new java.awt.Color(0, 51, 153));
        pFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        pUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Password_48px.png"))); // NOI18N
        pUsuario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-user-avatar-2.png"))); // NOI18N
        pUsuario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jTextFieldNome.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jTextFieldNome.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNome.setBorder(null);
        jTextFieldNome.setCaretColor(new java.awt.Color(0, 102, 204));
        jTextFieldNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pUsuario.add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 220, 30));

        jPasswordFieldSenha.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jPasswordFieldSenha.setForeground(new java.awt.Color(0, 51, 255));
        jPasswordFieldSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordFieldSenha.setBorder(null);
        jPasswordFieldSenha.setCaretColor(new java.awt.Color(0, 102, 204));
        jPasswordFieldSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pUsuario.add(jPasswordFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 220, 30));
        pUsuario.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 270, 10));
        pUsuario.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 270, 20));

        jLabelRedifinir.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelRedifinir.setForeground(new java.awt.Color(153, 153, 153));
        jLabelRedifinir.setText("Esquece a Palavra-Passe, Clica Aqui!");
        jLabelRedifinir.setToolTipText("");
        jLabelRedifinir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pUsuario.add(jLabelRedifinir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        jLabelSair.setBackground(new java.awt.Color(255, 153, 0));
        jLabelSair.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelSair.setForeground(new java.awt.Color(153, 153, 153));
        jLabelSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Close Window_48px.png"))); // NOI18N
        jLabelSair.setText("Fechar");
        jLabelSair.setToolTipText("");
        jLabelSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSairMouseClicked(evt);
            }
        });
        pUsuario.add(jLabelSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 150, 50));

        jLabelLogar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelLogar.setForeground(new java.awt.Color(153, 153, 153));
        jLabelLogar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Login Rounded Right_6px.png"))); // NOI18N
        jLabelLogar.setText("Entrar");
        jLabelLogar.setToolTipText("");
        jLabelLogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelLogarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelLogarMouseReleased(evt);
            }
        });
        pUsuario.add(jLabelLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, 50));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/ispm-log12.jpg"))); // NOI18N
        jLabel4.setText("Biblioteca ");
        pUsuario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 300, 60));

        pFundo.add(pUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(423, 473));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSairMouseClicked
        // Código para fechar o sistema
        this.dispose();
    }//GEN-LAST:event_jLabelSairMouseClicked

    private void jLabelLogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogarMouseClicked
        // Fazendo recolha de dados para logar:
        if(jTextFieldNome.getText().equals("admin") && jPasswordFieldSenha.getText().equals("123")){
            TelaSplash ts = new TelaSplash();
            ts.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Usuário e senha errada");
        }
       
    }//GEN-LAST:event_jLabelLogarMouseClicked

    private void jLabelLogarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogarMouseReleased
        ImageIcon lg = new ImageIcon(getClass().getResource("/icones/Login Rounded Right_64px.png"));
        jLabelLogar.setIcon(lg);
    }//GEN-LAST:event_jLabelLogarMouseReleased

    private void jLabelLogarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogarMousePressed
        ImageIcon lg = new ImageIcon(getClass().getResource("/icones/Login Rounded Right_6px.png"));
        jLabelLogar.setIcon(lg);
    }//GEN-LAST:event_jLabelLogarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelLogar;
    private javax.swing.JLabel jLabelRedifinir;
    private javax.swing.JLabel jLabelSair;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JPanel pFundo;
    private javax.swing.JPanel pUsuario;
    // End of variables declaration//GEN-END:variables
}
