/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DAOViews;

import DAOConection.Conexao;
import DAOControl.ControlFunc;
import DAOModel.ModelFunc;
import DAOModel.ModelTable;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Nolasco Dos Anjos
 */
public class TelaFunc extends javax.swing.JFrame {
    
    ModelFunc mf = new ModelFunc();
    ControlFunc cf = new ControlFunc();
    Conexao con = new Conexao();
    int flag = 0;
    /**
     * Creates new form TelaFunc
     */
    public TelaFunc() {
        initComponents();
        preencherTabela("select * from user order by nome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtBI = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtEmail = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxCateg = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFunc = new javax.swing.JTable();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        jLabelPesquisar = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txtSenha = new javax.swing.JPasswordField();
        txtConf = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CADASTRO FUNCIONÁRIO");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gênero:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, 20));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CADASTRO FUNCIONÁRIO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nº BI:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 30));

        txtCod.setBackground(new java.awt.Color(51, 102, 255));
        txtCod.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtCod.setForeground(new java.awt.Color(255, 255, 255));
        txtCod.setBorder(null);
        txtCod.setEnabled(false);
        jPanel1.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 50, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 50, 10));

        txtBI.setBackground(new java.awt.Color(51, 102, 255));
        txtBI.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtBI.setForeground(new java.awt.Color(255, 255, 255));
        txtBI.setBorder(null);
        txtBI.setEnabled(false);
        jPanel1.add(txtBI, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 200, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 200, 10));

        txtEmail.setBackground(new java.awt.Color(51, 102, 255));
        txtEmail.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(null);
        txtEmail.setEnabled(false);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 240, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 240, 10));

        jComboBoxGenero.setBackground(new java.awt.Color(51, 102, 255));
        jComboBoxGenero.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        jComboBoxGenero.setSelectedIndex(-1);
        jComboBoxGenero.setEnabled(false);
        jPanel1.add(jComboBoxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 60, 20));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nome:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        txtNome.setBackground(new java.awt.Color(51, 102, 255));
        txtNome.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setBorder(null);
        txtNome.setEnabled(false);
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 240, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 240, 10));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefone:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, 30));

        txtTel.setBackground(new java.awt.Color(51, 102, 255));
        txtTel.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtTel.setForeground(new java.awt.Color(255, 255, 255));
        txtTel.setBorder(null);
        txtTel.setEnabled(false);
        jPanel1.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 190, 20));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 190, 10));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cargo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, -1, -1));

        jComboBoxCateg.setBackground(new java.awt.Color(51, 102, 255));
        jComboBoxCateg.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxCateg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Bibliotecário" }));
        jComboBoxCateg.setSelectedIndex(-1);
        jComboBoxCateg.setEnabled(false);
        jPanel1.add(jComboBoxCateg, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 110, -1));

        jTableFunc.setBackground(new java.awt.Color(51, 102, 255));
        jTableFunc.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jTableFunc.setForeground(new java.awt.Color(255, 255, 255));
        jTableFunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableFunc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 930, 310));

        jButtonNovo.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNovo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Add User Group Woman Man_40px_1.png"))); // NOI18N
        jButtonNovo.setBorder(null);
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 30, 30));

        jButtonSalvar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Save.png"))); // NOI18N
        jButtonSalvar.setBorder(null);
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 30, 30));

        jButtonDeletar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDeletar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jButtonDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Delete_48px.png"))); // NOI18N
        jButtonDeletar.setBorder(null);
        jButtonDeletar.setEnabled(false);
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 30, 30));

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Close Window_48px_2.png"))); // NOI18N
        jButtonCancelar.setBorder(null);
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 30, 30));

        jButtonEditar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Edit File_40px.png"))); // NOI18N
        jButtonEditar.setBorder(null);
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 30, 30));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Código:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        jButton14.setBackground(new java.awt.Color(255, 255, 255));
        jButton14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Close Window_48px_2.png"))); // NOI18N
        jButton14.setBorder(null);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 30, 30));

        txtPesquisar.setBackground(new java.awt.Color(51, 102, 255));
        txtPesquisar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        txtPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        txtPesquisar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPesquisar.setBorder(null);
        jPanel1.add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 230, 30));

        jLabelPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Search_48px.png"))); // NOI18N
        jLabelPesquisar.setToolTipText("Procurar");
        jLabelPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPesquisarMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 40, 50));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 270, 10));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Senha:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 180, 10));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Confirmar senha:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, 30));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 170, 10));

        txtSenha.setBackground(new java.awt.Color(51, 102, 255));
        txtSenha.setBorder(null);
        txtSenha.setEnabled(false);
        jPanel1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 180, 20));

        txtConf.setBackground(new java.awt.Color(51, 102, 255));
        txtConf.setBorder(null);
        txtConf.setEnabled(false);
        jPanel1.add(txtConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 170, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(930, 531));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
      if(flag==1){
        mf.setNome(txtNome.getText());
        mf.setnBI(txtBI.getText());
        mf.setGenero(String.valueOf(jComboBoxCateg.getSelectedIndex()));
        mf.setTelefone(txtTel.getText());
        mf.setEmail(txtEmail.getText());
        mf.setCategoria(String.valueOf(jComboBoxGenero.getSelectedIndex()));
        mf.setLogar(txtNome.getText());
        mf.setSenha(String.valueOf(txtSenha.getPassword()));
        cf.salvar(mf);
        txtNome.setText("");
        txtBI.setText("");
        jComboBoxCateg.setSelectedIndex(-1);
        txtTel.setText("");
        txtEmail.setText("");
        jComboBoxCateg.setSelectedIndex(-1);
        txtSenha.setText("");
      }else{
          mf.setId((Integer.parseInt(txtCod.getText())));
          mf.setNome(txtNome.getText());
          mf.setnBI(txtBI.getText());
          mf.setGenero((String)jComboBoxGenero.getSelectedItem());
          mf.setTelefone(txtTel.getText());
          mf.setEmail(txtEmail.getText());
          mf.setCategoria((String)jComboBoxCateg.getSelectedItem());
          mf.setLogar(txtNome.getText());
          mf.setSenha(String.valueOf(txtSenha.getPassword()));
          cf.Editar(mf);
           txtCod.setText("");
           txtNome.setText("");
           txtBI.setText("");
           txtSenha.setText("");
           txtTel.setText("");
           txtEmail.setText("");
           jComboBoxGenero.setEnabled(false);
           jComboBoxCateg.setEnabled(false);
           txtSenha.setEnabled(false);
           jButtonNovo.setEnabled(true);
           jButtonCancelar.setEnabled(false);
           jButtonDeletar.setEnabled(false);
      } 
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        // Botão APAGAR:
        int resposta = 0;
        JOptionPane.showConfirmDialog(rootPane, "Deseja realmente eliminar Dados?");
        if(resposta == JOptionPane.YES_OPTION){
            mf.setId(Integer.parseInt(txtCod.getText()));
            cf.Apagar(mf);
            txtCod.setText("");
            txtNome.setText("");
            txtBI.setText("");
            txtSenha.setText("");
            txtTel.setText("");
            txtEmail.setText("");
        }
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // Botão Cancelar
        txtNome.setEnabled(!true);
        txtBI.setEnabled(!true);
        txtSenha.setEnabled(!true);
        txtConf.setEnabled(!true);
        txtEmail.setEnabled(!true);
        txtTel.setEnabled(!true);
        jComboBoxCateg.setEnabled(!true);
        jComboBoxGenero.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonCancelar.setEnabled(!true);
        jButtonEditar.setEnabled(false);
        jButtonDeletar.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // Código do botão NOVO para ativar os campos
       flag=1;
            txtNome.setEnabled(true);
            txtBI.setEnabled(true);
            txtSenha.setEnabled(true);
            txtConf.setEnabled(true);
            txtEmail.setEnabled(true);
            txtTel.setEnabled(true);
            jComboBoxCateg.setEnabled(true);
            jComboBoxGenero.setEnabled(true);
            jButtonSalvar.setEnabled(true);
            jButtonNovo.setEnabled(false);
            jButtonCancelar.setEnabled(true);
            txtNome.setText("");
            txtBI.setText("");
            jComboBoxCateg.setSelectedIndex(-1);
            txtTel.setText("");
            txtEmail.setText("");
            jComboBoxCateg.setSelectedIndex(-1);
            txtSenha.setText("");
       
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jLabelPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPesquisarMouseClicked
        // Codificando a label pesquisar
        mf.setPesquisa(txtPesquisar.getText());
        ModelFunc mfc = cf.buscarFunc(mf);
        txtNome.setText(mfc.getNome());
        txtCod.setText(String.valueOf(mfc.getId()));
        txtBI.setText(mfc.getnBI());
        jComboBoxGenero.setSelectedItem(mfc.getGenero());
        txtTel.setText(mfc.getTelefone());
        txtEmail.setText(mfc.getEmail());
        jComboBoxCateg.setSelectedItem(mfc.getCategoria());
        txtNome.setText(mfc.getNome());
        txtSenha.setText(mfc.getSenha());
        txtConf.setText(mfc.getSenha());
        jButtonEditar.setEnabled(true);
        jButtonDeletar.setEnabled(true);
    }//GEN-LAST:event_jLabelPesquisarMouseClicked

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        //Codificando o botão editar:
        flag=2;
        txtNome.setEnabled(true);
        txtBI.setEnabled(true);
        txtSenha.setEnabled(true);
        txtConf.setEnabled(true);
        txtEmail.setEnabled(true);
        txtTel.setEnabled(true);
        jComboBoxCateg.setEnabled(true);
        jComboBoxGenero.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String[]{"ID", "Nome", "NBI", "Gênero", "Contacto", "Email", "Cargo", "Utilizador", "Senha"};
        con.conexao();
        con.executSql(Sql);
        
        try {
            con.rs.first();
            do{
                dados.add(new Object[] {con.rs.getInt("id"),con.rs.getString("nome"),con.rs.getString("nBI"), con.rs.getString("sexo"),
                con.rs.getString("phone"),con.rs.getString("email"),con.rs.getString("category"),con.rs.getString("utilizador"),con.rs.getString("senha")});
            }while(con.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preecher Tabela"+ex);
        }
        ModelTable mt = new ModelTable(dados, colunas);
        jTableFunc.setModel(mt);
        jTableFunc.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTableFunc.getColumnModel().getColumn(0).setResizable(false);
        jTableFunc.getColumnModel().getColumn(1).setPreferredWidth(160);
        jTableFunc.getColumnModel().getColumn(1).setResizable(false);
        jTableFunc.getColumnModel().getColumn(2).setPreferredWidth(130);
        jTableFunc.getColumnModel().getColumn(2).setResizable(false);
        jTableFunc.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTableFunc.getColumnModel().getColumn(3).setResizable(false);
        jTableFunc.getColumnModel().getColumn(4).setPreferredWidth(130);
        jTableFunc.getColumnModel().getColumn(4).setResizable(false);
        jTableFunc.getColumnModel().getColumn(5).setPreferredWidth(160);
        jTableFunc.getColumnModel().getColumn(5).setResizable(false);
        jTableFunc.getColumnModel().getColumn(6).setPreferredWidth(95);
        jTableFunc.getColumnModel().getColumn(6).setResizable(false);
        jTableFunc.getColumnModel().getColumn(7).setPreferredWidth(102);
        jTableFunc.getColumnModel().getColumn(7).setResizable(false);
        jTableFunc.getColumnModel().getColumn(8).setPreferredWidth(69);
        jTableFunc.getColumnModel().getColumn(8).setResizable(false);
        jTableFunc.getTableHeader().setReorderingAllowed(false);
        jTableFunc.setAutoResizeMode(jTableFunc.AUTO_RESIZE_OFF);
        jTableFunc.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        con.desconectar();
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFunc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxCateg;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelPesquisar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTableFunc;
    private javax.swing.JTextField txtBI;
    private javax.swing.JTextField txtCod;
    private javax.swing.JPasswordField txtConf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
